# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from lib.share import SI

import ui.team.resource_rc
import ui.team.Login_sort as LS
from main import win_Main
import sys
from PyQt5.QtWidgets import QApplication,QLabel
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMargins, Qt

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Login_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)
        self.init_slots()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 489)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/用户.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAccessibleName("")
        Form.setStyleSheet("*{\n"
                           "\n"
                           "font-size:15px;\n"
                           "font-style:MingLiU-ExtB;\n"
                           "}\n"
                           "\n"
                           "QLineEdit\n"
                           "{\n"
                           "    background:white;\n"
                           "    padding-left:10px ;\n"
                           "    padding-top:1px ;\n"
                           "    border-bottom-left-radius:10px;\n"
                           "    border-top-left-radius:10px;\n"
                           "    border-top-right-radius:10px;\n"
                           "    \n"
                           "    font: 10pt \"宋体\";\n"
                           "    border-bottom-right-radius:10px;\n"
                           "   border: 2px solid rgb(159, 162, 162);\n"
                           "}\n"
                           "QLineEdit:hover\n"
                           "{\n"
                           "    padding-top:0px ;\n"
                           "    border: 1px solid rgb(21 , 131 , 221);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "\n"
                           "QCheckBox{\n"
                           "    background:rgba(85,170,255,0);\n"
                           "    color: rgb(0, 0, 0);\n"
                           "    font-style:MingLiU-ExtB;\n"
                           "}\n"
                           "QLabel{\n"
                           "font-style:MingLiU-ExtB;\n"
                           "font-size:14px;\n"
                           "}\n"
                           "QComboBox\n"
                           "{\n"
                           "    \n"
                           "    font: 10pt \"宋体\";\n"
                           "    background:white;\n"
                           "    padding-left:10px ;\n"
                           "    border-top-left-radius:10px;\n"
                           "    border-top-right-radius:10px;\n"
                           "    border-bottom-left-radius:10px;\n"
                           "    border-bottom-right-radius:10px;\n"
                           "    border: 2px solid rgb(159, 162, 162);\n"
                           "}\n"
                           "QComboBox:hover\n"
                           "{\n"
                           "    border: 1px solid rgb(21 , 131 , 221);\n"
                           "}\n"
                           "\n"
                           "QComboBox::down-arrow\n"
                           "{\n"
                           "    border-image:url(:/test/下箭头 (2).png);\n"
                           "    width:25px;\n"
                           "    height:25px;\n"
                           "}\n"
                           "QComboBox::down-arrow:hover\n"
                           "{\n"
                           "    border-image:url(:/test/下箭头 (2).png);\n"
                           "    width:30px;\n"
                           "    height:30px;\n"
                           "}\n"
                           "QComboBox::down-arrow:on\n"
                           "{\n"
                           "    border-image:url(:/test/下箭头 (2).png);\n"
                           "}\n"
                           "QComboBox::drop-down\n"
                           "{\n"
                           "    width:20px;\n"
                           "    background:transparent;\n"
                           "    padding-right:5px;\n"
                           "}\n"
                           "\n"
                           "")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 521, 491))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(255, 255, 255);\n"
                                 "background:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 210, 320, 40))
        self.lineEdit_2.setStyleSheet("\n"
                                      "color: rgb(0, 0, 0);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(100, 270, 91, 19))
        self.checkBox.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "font: 9pt \"宋体\";\n"
                                    "background:transparent;")
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(150, 330, 221, 50))
        self.pushButton.setStyleSheet("QPushButton\n"
                                      "{\n"
                                      "    border-radius:10px;\n"
                                      "    background-color: rgb(42,166,244);\n"
                                      "    font: 24pt \"黑体\";\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover\n"
                                      "{\n"
                                      "    \n"
                                      "    border-radius:10px;\n"
                                      "    background-color: rgb(135, 135, 135);\n"
                                      "    font: 24pt \"黑体\";\n"
                                      "}\n"
                                      "QPushButton:pressed\n"
                                      "{\n"
                                      "    \n"
                                      "    border-radius:10px;\n"
                                      "    background-color: rgb(255, 0, 0);\n"
                                      "    font: 24pt \"黑体\";\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(470, 0, 30, 30))
        self.toolButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_2.setStyleSheet("background:transparent;\n"
                                        "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 200, 80))
        self.label_2.setStyleSheet("background:transparent;\n"
                                   "font: 30pt \"黑体\";\n"
                                   "color: rgb(136, 136, 136);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(114, 400, 160, 30))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
                                   "font: 10pt \"宋体\";\n"
                                   "background:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(309, 400, 101, 30))
        self.label_5.setAcceptDrops(False)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
                                   "font: 10pt \"宋体\";\n"
                                   "background:transparent;")
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(90, 160, 320, 40))
        self.comboBox.setAccessibleName("")
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "\n"
                                    "")
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxCount(2147483646)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(263, 399, 50, 30))
        self.pushButton_3.setStyleSheet("\n"
                                        "QPushButton\n"
                                        "{\n"
                                        "    background:transparent;\n"
                                        "    color: rgb(255, 0, 0);\n"
                                        "    font: 10pt \"黑体\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover\n"
                                        "{\n"
                                        "    color: rgb(52, 52, 52);\n"
                                        "}\n"
                                        "QPushButton:pressed\n"
                                        "{\n"
                                        "    color: rgb(0, 0, 255);\n"
                                        "}\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 290, 93, 28))
        self.pushButton_2.setStyleSheet("\n"
                                        "QPushButton\n"
                                        "{\n"
                                        "    background:transparent;\n"
                                        "    color: rgb(0, 0, 255);\n"
                                        "    font: 9pt \"黑体\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover\n"
                                        "{\n"
                                        "    color: rgb(52, 52, 52);\n"
                                        "    font: 9pt \"黑体\";\n"
                                        "}\n"
                                        "QPushButton:pressed\n"
                                        "{\n"
                                        "    \n"
                                        "    color: rgb(170, 0, 0);\n"
                                        "    font: 9pt \"黑体\";\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.toolButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 521, 491))
        self.frame_2.setStyleSheet("image: url(:/test/榕创科技21302.png);\n"
                                   "background-color: rgb(255, 255, 255);\n"
                                   "")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.frame.raise_()

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(-1)
        self.toolButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "密码"))
        self.checkBox.setText(_translate("Form", "自动登录"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.toolButton_2.setText(_translate("Form", "close"))
        self.label_2.setText(_translate("Form", "欢迎登录"))
        self.label_3.setText(_translate("Form", "你还没有账号？那就"))
        self.label_5.setText(_translate("Form", "一个吧~"))
        self.comboBox.setPlaceholderText(_translate("Form", "账号"))
        self.comboBox.setItemText(0, _translate("Form", "qweqe"))
        self.comboBox.setItemText(1, _translate("Form", "qweqeqwe"))
        self.pushButton_3.setText(_translate("Form", "注册"))
        self.pushButton_2.setText(_translate("Form", "忘记密码？"))

    def init_slots(self):
        self.pushButton.clicked.connect(self.Log)
        self.pushButton_3.clicked.connect(self.slot_btn_function)

    def Find_Pwd(self):
        print("找回密码")


    def Log(self):
        self.id = self.comboBox.lineEdit().text()
        self.pwd = self.lineEdit_2.text()

        print(self.id,self.pwd)

        if self.id == "" or self.pwd == "":
            QtWidgets.QMessageBox.critical(self, u"Warning", u"请输入帐号或密码", buttons=QtWidgets.QMessageBox.Ok,
                                          defaultButton=QtWidgets.QMessageBox.Ok)

            '''
            messageBox = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Critical, "Warning", "请输入帐号或密码")
            messageBox.setWindowIcon(QtGui.QIcon("./ui/team/test.ico"))
            Qyes = messageBox.addButton(self.tr("设置"), QtWidgets.QMessageBox.YesRole)
            Qno = messageBox.addButton(self.tr("忽略"), QtWidgets.QMessageBox.NoRole)
            messageBox.exec_()
            if messageBox.clickedButton() == Qyes:
                print('ok')
            else:
                return
            '''

        else:
            self.login = LS.User_part()
            loginRes = self.login.Login(self.id,self.pwd)

            if not loginRes:
                QtWidgets.QMessageBox.warning(self, u"Warning", u"帐号或密码错误", buttons=QtWidgets.QMessageBox.Ok,
                                               defaultButton=QtWidgets.QMessageBox.Ok)
            else:
                SI.username = self.id
                SI.mainWin = win_Main()
                SI.mainWin.show()
                SI.loginWin.hide()

    def slot_btn_function(self):
        SI.loginWin.hide()
        SI.registerWin = Register_Form()
        SI.registerWin.show()

    def mouseMoveEvent(self, e: QMouseEvent):  # 重写移动事件
        self._endPos = e.pos() - self._startPos
        self.move(self.pos() + self._endPos)

    def mousePressEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = True
            self._startPos = QPoint(e.x(), e.y())

    def mouseReleaseEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = False
            self._startPos = None
            self._endPos = None

class Register_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 720)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 520, 720))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"        background-color: rgb(255, 255, 255);\n"  
"        border:1px solid;\n"
"        border-radius:10px;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    border-radius:10px;\n"
"    font: 10pt \"新宋体\";\n"
"    border-color: rgb(48, 48, 48);\n"
"    border:1px solid;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 14pt \"新宋体\";\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    border-color: rgb(109, 96, 255);\n"
"}\n"
"QLabel\n"
"{\n"
"    border:0px solid;\n"
"    font: 9pt \"黑体\";\n"
"    font: 11pt \"新宋体\";\n"
"\n"
"}\n"
"QPushButton\n"
"{\n"
"    color: rgb(0, 0, 255);\n"
"    background:transparent;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(165, 165, 165);\n"
"    background:transparent;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 40, 120, 40))
        self.label.setStyleSheet("color: rgb(163,163,164);\n"
"font: 16pt \"黑体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(12, 505, 80, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(12, 185, 60, 30))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(12, 425, 60, 30))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(12, 265, 80, 30))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(12, 105, 60, 30))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(12, 345, 60, 30))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(90, 100, 390, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 180, 390, 40))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 260, 390, 40))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 340, 390, 40))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 420, 390, 40))
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 500, 390, 40))
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(90, 560, 91, 30))
        self.checkBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(180, 560, 161, 30))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 560, 161, 30))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 620, 175, 40))
        self.pushButton_3.setStyleSheet("*{\n"
"    background-color: rgb(70, 70, 255);\n"
"    font: 16pt \"黑体\";\n"
"    color: rgb(255, 255, 255);\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"}\n"
"*:hover\n"
"{\n"
"    background-color: rgb(140, 133, 144);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 630, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(480, 10, 30, 30))
        self.toolButton.setStyleSheet("background:transparent;")
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.close) # type: ignore
        self.pushButton_3.clicked.connect(lambda: self.Crusers())
        self.pushButton_4.clicked.connect(lambda: self.slot_btn_function())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.label.setText(_translate("Form", "用户注册"))
        self.label_2.setText(_translate("Form", "确认密码"))
        self.label_3.setText(_translate("Form", "账号ID"))
        self.label_4.setText(_translate("Form", "密码"))
        self.label_5.setText(_translate("Form", "手机号码"))
        self.label_6.setText(_translate("Form", "用户名"))
        self.label_7.setText(_translate("Form", "邮箱"))
        self.checkBox.setText(_translate("Form", "我同意"))
        self.pushButton.setText(_translate("Form", "《榕创天眼服务协议》"))
        self.pushButton_2.setText(_translate("Form", "《榕创天眼隐私政策》"))
        self.pushButton_3.setText(_translate("Form", "确认注册"))
        self.pushButton_4.setText(_translate("Form", "返回登录"))

    def Crusers(self):
        self.name = self.lineEdit.text()
        self.id = self.lineEdit_2.text()
        self.phone = self.lineEdit_3.text()
        self.email = self.lineEdit_4.text()
        self.pwd = self.lineEdit_5.text()
        self.comfirm_pwd = self.lineEdit_6.text()

        flag = 0
        while True:
            if not self.name or not self.id or not self.phone or not self.email or not self.pwd or not self.comfirm_pwd:
                QtWidgets.QMessageBox.warning(self, u"Warning", u"请将信息填写完整！", buttons=QtWidgets.QMessageBox.Ok,
                                              defaultButton=QtWidgets.QMessageBox.Ok)
                break
            flag = 1
            break

        if flag:
            if not self.checkBox.isChecked():
                QtWidgets.QMessageBox.warning(self, u"Warning", u"请勾选服务协议！", buttons=QtWidgets.QMessageBox.Ok,
                                              defaultButton=QtWidgets.QMessageBox.Ok)
                return
            if self.pwd == self.comfirm_pwd and self.pwd != "":
                self.register = LS.User_part()
                registerRes = self.register.CUsers(self.email,self.id,self.pwd,self.phone,self.name)
                if not registerRes:
                    QtWidgets.QMessageBox.warning(self, u"Warning", u"注册失败！", buttons=QtWidgets.QMessageBox.Ok,
                                                  defaultButton=QtWidgets.QMessageBox.Ok)
                else:
                    QtWidgets.QMessageBox.warning(self, u"Warning", u"恭喜您注册成功！", buttons=QtWidgets.QMessageBox.Ok,
                                                  defaultButton=QtWidgets.QMessageBox.Ok)
                    SI.loginWin.show()
                    SI.registerWin.close()
            else:
                QtWidgets.QMessageBox.warning(self, u"Warning", u"密码不一致！请重新输入密码！", buttons=QtWidgets.QMessageBox.Ok,
                                              defaultButton=QtWidgets.QMessageBox.Ok)

    def slot_btn_function(self):
        SI.registerWin.close()
        SI.loginWin.show()

    def mouseMoveEvent(self, e: QMouseEvent):  # 重写移动事件
        self._endPos = e.pos() - self._startPos
        self.move(self.pos() + self._endPos)

    def mousePressEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = True
            self._startPos = QPoint(e.x(), e.y())

    def mouseReleaseEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = False
            self._startPos = None
            self._endPos = None

if __name__ == '__main__':
    app=QApplication(sys.argv)
    SI.loginWin=Login_Form()
    SI.loginWin.show()
    sys.exit(app.exec_())