# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suggest.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import ui.team.resource_rc
import ui.team.Login_sort as LS
import sys
from PyQt5.QtWidgets import QApplication,QLabel
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMargins, Qt

class suggest_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 429)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 539, 429))
        self.frame.setStyleSheet("*{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(239,239,239, 255), stop:1 rgba(248,248,248, 255));\n"
"}\n"
"QPushButton\n"
"{\n"
"    border:0px;\n"
"}\n"
"QLabel\n"
"{\n"
"    border:0px;\n"
"}\n"
"QToolButton\n"
"{\n"
"    border:0px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(15, 12, 64, 17))
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(506, 10, 31, 20))
        self.toolButton.setStyleSheet("background:transparent;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(475, 10, 31, 20))
        self.toolButton_2.setStyleSheet("background:transparent;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/test/最小化 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setObjectName("toolButton_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 540, 390))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(172, 172, 172);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 240, 240, 125))
        self.pushButton_3.setStyleSheet("*{\n"
"    image: url(:/test/建议.png);\n"
"    background:transparent;\n"
"}\n"
"*:pressed{\n"
"    border:1px solid;\n"
"    border-radius:0px;\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 70, 240, 125))
        self.pushButton_4.setStyleSheet("*{\n"
"    image: url(:/test/夸赞.png);\n"
"    background:transparent;\n"
"}\n"
"*:pressed{\n"
"    border:1px solid;\n"
"    border-radius:0px;\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 70, 240, 125))
        self.pushButton_5.setStyleSheet("*{\n"
"    image: url(:/test/吐槽.png);\n"
"    background:transparent;\n"
"}\n"
"*:pressed{\n"
"    border:1px solid;\n"
"    border-radius:0px;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 240, 240, 125))
        self.pushButton_6.setStyleSheet("*{\n"
"    image: url(:/test/求助.png);\n"
"    background:transparent;\n"
"}\n"
"*:pressed{\n"
"    border:1px solid;\n"
"    border-radius:0px;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")


        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.label.setText(_translate("Form", "意见留言"))
        self.toolButton.setText(_translate("Form", "..."))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.pushButton_3.clicked.connect(lambda: self.jianyi())
        self.pushButton_4.clicked.connect(lambda: self.kuazan())
        self.pushButton_5.clicked.connect(lambda: self.tucao())
        self.pushButton_6.clicked.connect(lambda: self.qiuzhu())

    def jianyi(self):
        print("建议1")
        self.jianyi_page = jianyi_Form()
        self.jianyi_page.show()
    def kuazan(self):
        print("夸赞")
        self.kuazan_page = kuazan_Form()
        self.kuazan_page.show()
    def tucao(self):
        print("吐槽")
        self.tucao_page = tucao_Form()
        self.tucao_page.show()
    def qiuzhu(self):
        print("求助")
        self.qiuzhu_page = qiuzhu_Form()
        self.qiuzhu_page.show()

class kuazan_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 390)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 390))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: rgb(238,238,238);\n"
"}\n"
"QLabel\n"
"{\n"
"    border:0px;\n"
"    \n"
"    font: 9pt \"新宋体\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 5, 30, 30))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 500, 350))
        self.frame_2.setStyleSheet("*{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 131, 30))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 240, 140, 45))
        self.pushButton.setStyleSheet("*{\n"
"    background-color: rgb(213,213,213);\n"
"    border:0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"*:hover\n"
"{\n"
"\n"
"    border:1px solid;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 460, 150))
        self.textEdit.setStyleSheet("*{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    border-color: rgb(225,225,225);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(470, 10, 20, 20))
        self.toolButton.setStyleSheet("*{\n"
"    border:0px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.close) # type: ignore
        self.pushButton.clicked.connect(lambda: self.tijiao())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "夸赞"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.label.setText(_translate("Form", "夸赞"))
        self.label_3.setText(_translate("Form", "请输入您的好评："))
        self.pushButton.setText(_translate("Form", "提交"))
        self.toolButton.setText(_translate("Form", "关闭"))

    def tijiao(self):
        self.kuazan_text = self.textEdit.toPlainText()
        print(self.kuazan_text)

class jianyi_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 440)
        Form.setStyleSheet("QFrame\n"
"{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: rgb(238,238,238);\n"
"}\n"
"QLabel\n"
"{\n"
"    border:0px;\n"
"    \n"
"    font: 9pt \"新宋体\";\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 440))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 5, 30, 30))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 500, 400))
        self.frame_2.setStyleSheet("*{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 25, 121, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 131, 30))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 70, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 120, 121, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(160, 120, 131, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(160, 70, 91, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 70, 91, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 320, 140, 45))
        self.pushButton.setStyleSheet("*{\n"
"    background-color: rgb(213,213,213);\n"
"    border:0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"*:hover\n"
"{\n"
"\n"
"    border:1px solid;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 190, 460, 100))
        self.textEdit.setStyleSheet("*{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    border-color: rgb(225,225,225);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(470, 10, 20, 20))
        self.toolButton.setStyleSheet("*{\n"
"    border:0px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.close) # type: ignore
        self.pushButton.clicked.connect(lambda: self.tijiao())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "建议"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.label.setText(_translate("Form", "建议"))
        self.label_2.setText(_translate("Form", "请选择建议类型："))
        self.label_3.setText(_translate("Form", "请输入您的建议："))
        self.checkBox.setText(_translate("Form", "视频播放"))
        self.checkBox_2.setText(_translate("Form", "软件界面操作"))
        self.checkBox_3.setText(_translate("Form", "其它方面的建议"))
        self.checkBox_4.setText(_translate("Form", "录像查看"))
        self.checkBox_5.setText(_translate("Form", "告警消息"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.toolButton.setText(_translate("Form", "关闭"))

    def tijiao(self):
        self.jianyi_text = self.textEdit.toPlainText()
        print(self.jianyi_text)

class tucao_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 560)
        Form.setStyleSheet("QFrame\n"
"{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: rgb(238,238,238);\n"
"}\n"
"QLabel\n"
"{\n"
"    border:0px;\n"
"    \n"
"    font: 9pt \"新宋体\";\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 560))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 5, 30, 30))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 500, 520))
        self.frame_2.setStyleSheet("*{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 101, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 131, 30))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 70, 191, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 120, 181, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 170, 191, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 70, 181, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setGeometry(QtCore.QRect(280, 120, 161, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 400, 140, 45))
        self.pushButton.setStyleSheet("*{\n"
"    background-color: rgb(213,213,213);\n"
"    border:0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"*:hover\n"
"{\n"
"\n"
"    border:1px solid;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 240, 460, 100))
        self.textEdit.setStyleSheet("*{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    border-color: rgb(225,225,225);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(470, 10, 20, 20))
        self.toolButton.setStyleSheet("*{\n"
"    border:0px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.close)  # type: ignore
        self.pushButton.clicked.connect(lambda: self.tijiao())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "吐槽"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.label.setText(_translate("Form", "吐槽"))
        self.label_2.setText(_translate("Form", "请您尽情吐槽！"))
        self.label_3.setText(_translate("Form", "请输入您的问题："))
        self.checkBox.setText(_translate("Form", "视频预览、录像回放卡顿"))
        self.checkBox_2.setText(_translate("Form", "报警消息经常漏报误报"))
        self.checkBox_3.setText(_translate("Form", "其他原因，可在下方注明"))
        self.checkBox_4.setText(_translate("Form", "断网、掉线、黑屏屏蔽"))
        self.checkBox_5.setText(_translate("Form", "软件功能少，不好用"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.toolButton.setText(_translate("Form", "关闭"))

    def tijiao(self):
        self.tucao_text = self.textEdit.toPlainText()
        print(self.tucao_text)

class qiuzhu_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 390)
        Form.setAccessibleName("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 390))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: rgb(238,238,238);\n"
"}\n"
"QLabel\n"
"{\n"
"    border:0px;\n"
"    \n"
"    font: 9pt \"新宋体\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 5, 30, 30))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 500, 350))
        self.frame_2.setStyleSheet("*{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 131, 30))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 240, 140, 45))
        self.pushButton.setStyleSheet("*{\n"
"    background-color: rgb(213,213,213);\n"
"    border:0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"*:hover\n"
"{\n"
"\n"
"    border:1px solid;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 460, 150))
        self.textEdit.setStyleSheet("*{\n"
"    border:1px solid;\n"
"    border-radius:10px;\n"
"    border-color: rgb(225,225,225);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(470, 10, 20, 20))
        self.toolButton.setStyleSheet("*{\n"
"    border:0px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.close)  # type: ignore
        self.pushButton.clicked.connect(lambda: self.tijiao())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.label.setText(_translate("Form", "求助"))
        self.label_3.setText(_translate("Form", "请输入您的求助："))
        self.pushButton.setText(_translate("Form", "提交"))
        self.toolButton.setText(_translate("Form", "关闭"))

    def tijiao(self):
        self.qiuzhu_text = self.textEdit.toPlainText()
        print(self.qiuzhu_text)

if __name__ == '__main__':
    app=QApplication(sys.argv)
    ex=suggest_Form()
    ex.show()
    sys.exit(app.exec_())